In [36]:
import numpy as np
from IPython.display import Markdown
import numpy.linalg as LA

In [24]:
import matplotlib.pyplot as plt

In [25]:
def fact(n):
    return np.prod(np.arange(1,n+1),axis=0)

In [26]:
def fact_approx(n):
    return np.sqrt(2*np.pi*n) * (n/np.e)**n

In [34]:
tstr = ""
tstr += f"n | n! | $F_n$ | Absolute Error | Relative error\n"
tstr += f"---|---|---|---|---|\n"
for n in range(1,21):
    tstr+= f"{n} |  {fact(n)} | {fact_approx(n)} | {np.abs(fact_approx(n)- fact(n))} | {np.abs(fact_approx(n)- fact(n))/fact(n)}\n"
display(Markdown(tstr))

n | n! | $F_n$ | Absolute Error | Relative error
---|---|---|---|---|
1 |  1 | 0.9221370088957891 | 0.07786299110421091 | 0.07786299110421091
2 |  2 | 1.9190043514889832 | 0.08099564851101682 | 0.04049782425550841
3 |  6 | 5.836209591345864 | 0.16379040865413597 | 0.027298401442355995
4 |  24 | 23.506175132893294 | 0.4938248671067065 | 0.020576036129446102
5 |  120 | 118.0191679575901 | 1.9808320424099009 | 0.016506933686749173
6 |  720 | 710.078184642185 | 9.921815357815035 | 0.013780299108076438
7 |  5040 | 4980.395831612462 | 59.604168387538266 | 0.011826223886416323
8 |  40320 | 39902.39545265671 | 417.6045473432896 | 0.010357255638474444
9 |  362880 | 359536.87284194835 | 3343.1271580516477 | 0.009212762230080598
10 |  3628800 | 3598695.6187410373 | 30104.381258962676 | 0.008295960443938127
11 |  39916800 | 39615625.05057755 | 301174.9494224489 | 0.007545067475911117
12 |  479001600 | 475687486.47277606 | 3314113.5272239447 | 0.006918794273806068
13 |  6227020800 | 6187239475.19272 | 39781324.80727959 | 0.006388500389669421
14 |  87178291200 | 86661001740.59883 | 517289459.4011688 | 0.005933695789177946
15 |  1307674368000 | 1300430722199.468 | 7243645800.531982 | 0.00553933454519771
16 |  20922789888000 | 20814114415223.137 | 108675472776.86328 | 0.005194119587235004
17 |  355687428096000 | 353948328666101.1 | 1739099429898.875 | 0.004889403708217352
18 |  6402373705728000 | 6372804626194313.0 | 29569079533687.0 | 0.0046184557310724435
19 |  121645100408832000 | 1.2111278659229419e+17 | 532313816537808.0 | 0.004375957722495822
20 |  2432902008176640000 | 2.422786846761135e+18 | 1.0115161415504896e+16 | 0.0041576526228797


In [35]:
def g(v):
    x,y= v[0],v[1]
    return np.array([x**2 + (y**2/9.) -1.,(x**2/4.) + y**2 - 1.])
def J_g(v):
    x,y = v[0], v[1]
    return np.array([[2*x,(2*y/9.)],[x/2., 2*y]])

In [45]:
def NewtonSolve(x0,tol,maxIter):
    x = x0
    i =0 
    while LA.norm(g(x)) > tol and i < maxIter:
        x += LA.solve(J_g(x),-g(x))
        i+=1
    return x, i

In [43]:
NewtonSolve(np.array([1.,1.]), 1e-15, 20 )

(array([0.95618289, 0.87831007]), 4)

In [44]:
g(np.array([0.95618289, 0.87831007]))

array([5.69135272e-09, 8.84559315e-09])

In [48]:
def BroydenMethod(x0,B0,tol, maxIter):
    x = x0
    B = B0
    i =0  
    while LA.norm(g(x)) > tol and i < maxIter:
        s = LA.solve(B,-g(x))
        x +=s
        B += np.outer(g(x),s)/(s@s)
        i+=1
    return x,i

In [62]:
BroydenMethod(np.array([1.,1.]),np.random.random((2,2)),1e-14,30)

(array([0.95618289, 0.87831007]), 13)